### ISSUE TITLE
Saved status are not readable...

### ISSUE THREAD

**Issue by sultansharma** [AkramChauhan/WhatsApp-Status-Downloader-using-Flutter#1]
Sir , all things working fine but when we save any status its not came to gallery or not videos are not playable , 
after saving if we rename/move/copy etc. to file then file is readable otherwise its not working,

please suggest a better way to save the file....

**Comment by AkramChauhan** [comment]
Can you give me more information about which device you are using?
I will cross-check and fix the issue.
-Thanks.

**Comment by sultansharma** [comment]
Am testing app on my samsung m-20
, For devloping am using windows-10 laptop and VSCode..

All working fine but when we save any status , - its copied to our
mentioned folder(not coming to galary or video not playable from that
folder also)

I tried : - * Changing file saving(copy) location (not working)
*Saving file with simple name without $curdate (not working)


---if we rename or move file from filemanager after saving in folder then
its start coming in galary also..

Bro i need solution for that....

**Comment by AkramChauhan** [comment]
I've updated the repo.
Added new dependency to save images in the gallery.

[Click Here to see file changes](https://github.com/AkramChauhan/WhatsApp-Status-Downloader-using-Flutter/commit/32bcd79eee2d7211a320aaca5e5ebc247ec55709)

**Comment by sultansharma** [comment]
Thankx !

Any update for videos ?, they are not coming to gallery as well as not
readable from filemanager.

**Comment by AkramChauhan** [comment]
Videos are still not coming in Gallery,
I am finding a solution for that.

Videos are now readable in FileManager.

**Comment by AkramChauhan** [comment]
As this issue was created because images and videos were not readable. But now those are readable that's why Closing this Issue. :)
