### ISSUE TITLE
Not found in play store.

### ISSUE THREAD

**Issue by abkoradiya** [AkramChauhan/WhatsApp-Status-Downloader-using-Flutter#2]
Any issue is there with privacy & policy ?

**Comment by AkramChauhan** [comment]
No There is no Issue with this Application.
My Main Account got suspended because of 3 strikes in account.

**Comment by AkramChauhan** [comment]
I will deploy it in another Developer Account and Update the PlayStore Link. :)

**Comment by AkramChauhan** [comment]
Account associated with this application suspended due to rejection of other application.

**Comment by B-Anupam** [comment]
Was the account suspended due to this application?

**Comment by AkramChauhan** [comment]
Ofcourse, not.
