### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by moh1122** [AkramChauhan/WhatsApp-Status-Downloader-using-Flutter#3]
Hello
on iOS I already have WhatsApp installed but im getting a message saying that WhatsApp is not installed?
any clue how to fix this?

**Comment by AkramChauhan** [comment]
Currently, its not optimized for iOS. I didn't have resources like Apple Devices to test and build release for this test project.
Someone who is already having Apple device can do minor fixes and submit pull request.
I would love to consider that one.

Regards
