### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by muntazir143** [AkramChauhan/WhatsApp-Status-Downloader-using-Flutter#4]
This app is not working on devices running android 10 & above. Can you please update your code?

**Comment by AkramChauhan** [comment]
I got busy with something, I Will try updating repository.

**Comment by AkramChauhan** [comment]
Added support for Android 10, 11, 12 
[Merged](https://github.com/AkramChauhan/WhatsApp-Status-Downloader-using-Flutter/pull/5)

**Comment by muntazir143** [comment]
Thanks I'll definitely look into it.
